name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Configure Git
        run: |
          git config --global credential.helper store
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global advice.detachedHead false
          mkdir -p "${HOME}/.config/git"
      - name: Run Tests
        run: |
          bundle install --jobs=3 --retry=3 --deployment
          bundle exec rake
